import { Schema, model } from 'mongoose'

const base = { shopId: { type: String, required: true, index: true }, createdAt: { type: Date, default: Date.now }, updatedAt: { type: Date, default: Date.now } }
export const UserModel = model('User', new Schema({ ...base, userId: { type: String, unique: true }, name: String, phone: { type: String, required: true, index: true }, email: { type: String, index: true }, passwordHash: String, role: { type: String, enum: ['OWNER', 'MANAGER', 'STAFF'], default: 'STAFF' } }))
export const ShopModel = model('Shop', new Schema({ shopId: { type: String, unique: true }, name: String, phone: String, address: String, upiId: String, payeeName: String, interestSettings: { enabled: Boolean, rate: Number, ratePeriod: String, gracePeriod: Number } }))
export const CustomerModel = model('Customer', new Schema({ ...base, customerId: { type: String, unique: true }, name: String, phone: String, openingBalance: { type: Number, default: 0 }, creditLimit: Number, interestEnabled: Boolean, interestRate: Number, notes: String }))
export const ProductModel = model('Product', new Schema({ ...base, productId: { type: String, unique: true }, name: String, sku: String, barcode: String, category: String, brand: String, unit: String, purchasePrice: Number, sellingPrice: Number, minimumStock: Number, supplierId: String, description: String, currentStock: { type: Number, default: 0 } }))
export const LedgerTransactionModel = model('LedgerTransaction', new Schema({ ...base, transactionId: { type: String, unique: true }, customerId: String, type: String, direction: String, amount: Number, referenceId: String, description: String }))
export const StockMovementModel = model('StockMovement', new Schema({ ...base, transactionId: { type: String, unique: true }, productId: String, quantity: Number, type: String, direction: String, referenceId: String, notes: String }))
export const SaleModel = model('Sale', new Schema({ ...base, saleId: { type: String, unique: true }, customerId: String, items: Schema.Types.Mixed, subtotal: Number, discount: Number, tax: Number, total: Number, paymentMethod: String, paymentStatus: String, transactionId: { type: String, unique: true } }))
export const PaymentModel = model('Payment', new Schema({ ...base, paymentId: { type: String, unique: true }, saleId: String, customerId: String, ledgerTransactionId: String, amount: Number, status: String, provider: String, transactionReference: String, transactionId: { type: String, unique: true }, verifiedAt: Date }))
export const SupplierModel = model('Supplier', new Schema({ ...base, supplierId: { type: String, unique: true }, name: String, phone: String, email: String, address: String, gstNumber: String, paymentTerms: String, notes: String }))
export const PurchaseOrderModel = model('PurchaseOrder', new Schema({ ...base, purchaseOrderId: { type: String, unique: true }, supplierId: String, items: Schema.Types.Mixed, estimatedTotal: Number, status: String, transactionId: { type: String, unique: true } }))
export const SyncEventModel = model('SyncEvent', new Schema({ transactionId: { type: String, unique: true }, shopId: { type: String, index: true }, entityId: String, endpoint: String, payload: Schema.Types.Mixed, createdAt: { type: Date, default: Date.now } }))
